// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxGDLyhEU3AnpDgZ0-oXnGPGAoeYMTsoY',
    appId: '1:12341172616:web:c246443b203e7e5061823d',
    messagingSenderId: '12341172616',
    projectId: 'todoapp-f5ad9',
    authDomain: 'todoapp-f5ad9.firebaseapp.com',
    storageBucket: 'todoapp-f5ad9.appspot.com',
    measurementId: 'G-XZK2R3MFLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBy-8UeIbi0om4P-qWPjaHUHCzXdfEBpg',
    appId: '1:12341172616:android:8eafb51424c1c1fd61823d',
    messagingSenderId: '12341172616',
    projectId: 'todoapp-f5ad9',
    storageBucket: 'todoapp-f5ad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuD5Vwr2MqrAzwEa38RNd6il5dH_S4FNY',
    appId: '1:12341172616:ios:89c90f3fc9cbb9c461823d',
    messagingSenderId: '12341172616',
    projectId: 'todoapp-f5ad9',
    storageBucket: 'todoapp-f5ad9.appspot.com',
    iosBundleId: 'com.example.todotask',
  );
}
